Update autostart

diff --git a/resources/autostart b/resources/autostart
--- a/resources/autostart
+++ b/resources/autostart
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-echo "autostart started at $(date)"
+source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }
 
 if [[ "$RUN_BY_CRON"  == "TRUE" ]]; then
-	sleep 10
+	sleep $AUTOSTARTDELAY
 fi
-
-source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }
 
 if [[ ! -f "$HOME/autostart.list" ]]; then
 	echoerr "could not find $HOME/autostart.list"
