Update config

diff --git a/resources/config b/resources/config
--- a/resources/config
+++ b/resources/config
@@ -2,9 +2,32 @@
 
 # changes server configuration (via server.properties) with a text GUI
 
+source "$HOME/bin/_check" || { echo "error: $HOME/bin/_check not found or readable"; exit 1; }
+
 if [[ "$#" -lt 1 ]]; then
     echoerr "too few parameters. Usage: $0 <servername>"
     exit 1
+fi
+
+servername="$1"
+xlabel=3
+xitem=18
+y=1 # incremental
+
+cd "$MCPATH" || {
+    echoerr "could not enter $MCPATH"
+    exit 1
+}
+
+cd "$servername" || {
+    echoerr "server $servername not found at $MCPATH/$servername"
+    exit 1
+}
+
+if [[ ! -f server.properties ]]; then
+    echoerr "could not find server.properties at $MCPATH/$servername."
+    echoerr "did you start the server at least once?"
+    exit 2
 fi
 
 while read line; do
@@ -13,23 +36,7 @@ while read line; do
     echo $key: $value
 done < server.properties
 
-dialog --title "JEFF-MC: Configuring Server $servername" \
-        --form "\nCopyright 2017 JEFFmedia GbR\n\n
-Eingebeformate:\n
-- Zauber: z.B. looting:3,feather_falling:1,...\n
-- Trank: z.B. strong_healing\n
-- Damage: z.B. 5 (für grüne Wolle)
-\n\nBlockdata-Command generieren:" 30 56 12 \
-        "       Item:" 1 3 "$def_item"   1 18 30 50 \
-        "     Anzahl:" 2 3 "$def_anzahl" 2 18 3 2 \
-        "       Name:" 3 3 "$def_name"   3 18 30 50 \
-        "    Hinweis:" 4 3 "$def_lore"   4 18 30 500 \
-        "     Zauber:" 5 3 "$def_ench" 5 18 30 500 \
-        "      Trank:" 6 3 "$def_trank" 6 18 30 50 \
-        "     Damage:" 7 3 "$def_dmg" 7 18 5 5 \
-        "Extra-Daten:" 8 3 "$def_xdata"  8 18 30 5000 \
-        "Kistengröße:" 9 3 "$def_kistengroesse" 9 18 3 2 \
-        "          X:" 10 3 "$def_x"      10 18 10 10 \
-        "          Y:" 11 3 "$def_y"      11 18 10 10 \
-        "          Z:" 12 3 "$def_z"      12 18 10 10 \
-        2>~/.jeff.mcgenchest.tmp.$$
+dialog --title "JEFF-MC: Server configuration" \
+        --form "\nCopyright 2018 JEFFmedia GbR" $(($(tput lines)-6)) $(($(tput cols)-6)) $(($(tput lines)-20)) \
+        "Prop1" $y $xlabel "true"   $y $xitem 30 50 \
+        2>/tmp/jeffmc.$$
